# Generated by Django 2.0.3 on 2018-04-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180401_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdd',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
